# Setup
title:               INFORMATIKA UMMU
tagline:             ''
# tagline:             'Page Of KP 2023 Informatika UMMU'
description:         'Halaman Informasi Untuk KP-2023 Prodi Informatika UMMU Ternate Malut.'
url:                 https://infoummu.github.io/kp2023/
baseurl:             ''
paginate:            5
# permalink:           pretty
permalink:           /:title

# About/contact
author:
  name:              Informatika-UMMU
  url:               https://twitter.com/infoummu
  email:             info.ummu@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
# version:             1.1.0
google_analytics_id: #UA-XXXX-Y
